### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ryantm** [Synthetica9/nixpkgs-update-github-releases#2]
Preferably the license would be CC0 1.0 so we can integrate it with nixpkgs-update trivially

https://github.com/ryantm/nixpkgs-update/blob/master/LICENSE

I hereby license my contributions to this repository under:
Creative Commons Zero v1.0 Universal (SPDX Short Identifier: CC0-1.0)

**Comment by Synthetica9** [comment]
Oh, yeah, sure, cc0 is fine

**Comment by Synthetica9** [comment]
Closed via 9f84ad29d6cc6846aea9eb22f312dc45da26b823
