### ISSUE TITLE
transfer repository to nix-community

### ISSUE THREAD

**Issue by zowoq** [Synthetica9/nixpkgs-update-github-releases#9]
We're trying to consolidate everything related to the nixpkgs-update bot (https://github.com/nix-community/infra/issues/984), would you be okay with transferring this repository to the nix-community organisation?

**Comment by Synthetica9** [comment]
Oh yeah I hadn't really thought about this repo in years, would be more
than happy to

**Comment by zowoq** [comment]
Great, thanks! I've sent you an invite to the nix-community organisation, then you should be able to transfer the repo.

**Comment by zowoq** [comment]
Thank you.

**Comment by Synthetica9** [comment]
I'll also merge the open PR in Ryan's fork, since the head of that seems to be the canonical (deployed) version at the moment

**Comment by zowoq** [comment]
I've got a couple of small patches in addition PR that are also deployed, I'll open a separate PR for them.
